// The Collection entity.
// The single most important model in this entire codebase.
// Every NFT collection ever created through this launchpad — its name, its creator,
// its mint timeline, its phases, its treasury receivers, its on-chain address —
// all of it lives in this class. All of it is persisted in the PostgreSQL table
// named "Collection", exactly as decorated below.
//
// This is the sacred data. Treat it with the gravity it deserves.
// Or don't. But then don't come to Juan when the schema migration fails.

// TypeORM column and table decorators — the annotations that tell the ORM
// how to map these TypeScript properties to PostgreSQL columns.
import {
  Entity,                 // Declares this class as a database entity — maps to a table
  Column,                 // A regular database column — the bread and butter
  PrimaryGeneratedColumn, // Auto-generated UUID primary key — no manual IDs here
  CreateDateColumn,       // Automatically populated on INSERT — createdAt managed by TypeORM
  UpdateDateColumn,       // Automatically updated on every UPDATE — updatedAt managed by TypeORM
  DeleteDateColumn,       // For soft deletes — populated on softDelete(), null means not deleted
  Index,                  // Creates a database index — for the queries that need to be fast
} from 'typeorm';

/**
 * CollectionStatus
 *
 * The lifecycle states a collection moves through from idea to completion.
 * Stored as a string enum in the database with a CHECK constraint (migration 20260605000001)
 * ensuring only valid values are ever persisted.
 *
 * Enum gives compile-time type safety here in TypeScript.
 * The DB constraint provides the last line of defense at storage time.
 * Belt and suspenders. Both required.
 * (The blockchain does not offer a refund on wrong statuses.)
 */
export enum CollectionStatus {
  DRAFT     = 'draft',      // Just created — the collection exists in spirit and ambition only
  PREPARING = 'preparing',  // Configuration in progress — phases, prices, and fund receivers being set
  READY     = 'ready',      // Fully configured — mint hasn't started yet but the countdown has meaning
  MINTING   = 'minting',    // Active mint window — tokens are being claimed, money is flowing
  COMPLETED = 'completed',  // Sold out or mint ended — the collection has made its mark on the chain
  PAUSED    = 'paused',     // Temporarily suspended — for emergencies, upgrades, or second thoughts
}

/**
 * Collection
 *
 * The TypeORM entity for the Collection table. Maps to the PostgreSQL table "Collection"
 * (note: capital C — the table was created this way and we respect history).
 *
 * This entity holds everything about an NFT collection:
 * - Identity:   name, slug, description, creator
 * - Assets:     imageUrl, bannerUrl (URLs pointing to IPFS or CDN)
 * - On-chain:   mintAddress, creatorAddress, blockchain, txSignature
 * - Economics:  price, royaltyBasisPoints, platformFeeBasisPoints, fundReceivers
 * - Timeline:   mintStart, endDate, phases
 * - Status:     status (enum), effectiveStatus (resolved, for fast DB filtering)
 * - Metadata:   traits, social links, featured flag
 * - Audit:      createdAt, updatedAt, updatedBy, deletedAt (soft delete)
 *
 * Every field has a reason to exist. Some have two. (Looking at you, effectiveStatus.)
 */
@Entity('Collection')  // Table name: 'Collection'. Uppercase. It was decided. We honor it.
export class Collection {
  /**
   * Primary key — a UUID generated by the database on INSERT.
   * UUIDs: globally unique, unguessable by outsiders, safe to expose in URLs.
   * Auto-increment integers: fine for a blog. Not for an NFT launchpad with public APIs.
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * The slug — a URL-friendly, human-readable identifier for this collection.
   * Used in frontend routes like /collection/nexus-genesis
   * Generated from the name via slug.util.ts, deduplicated against existing slugs.
   * Unique constraint implicitly creates a B-tree index — fast lookups, uniqueness guaranteed.
   */
  @Column({ unique: true })
  slug: string; // Human-readable URL identifier — unique constraint creates the index

  /**
   * The collection name — what humans call it.
   * Not required to be unique (two teams can both make "Genesis Collection").
   * Covered by a GIN trigram index (idx_collection_name_trgm) for ILIKE search —
   * the B-tree index was dropped in migration 000019 in favor of the trgm index.
   */
  @Column()
  name: string; // GIN trgm index (idx_collection_name_trgm) covers ILIKE — B-tree dropped in migration 000019

  /**
   * The description — marketing copy, lore, or whatever the creator wrote at midnight.
   * Stored as `text` (unbounded) because artists have feelings and sometimes those
   * feelings are 10,000 characters long.
   */
  @Column('text')
  description: string;

  /**
   * Primary image URL — the collection's cover art.
   * Typically an IPFS gateway URL (https://ipfs.io/ipfs/Qm...) or CDN URL.
   * This is what marketplaces display as the collection thumbnail.
   * Make it good. Make it permanent. Make it IPFS.
   */
  @Column()
  imageUrl: string;

  /**
   * Banner URL — the wide hero image shown at the top of the collection page.
   * Optional: not every collection has a banner. The ones that do look more professional.
   * No pressure. But also: have a banner.
   */
  @Column({ nullable: true })
  bannerUrl?: string;

  /**
   * Creator display name — the human being behind the NFTs.
   * Not validated against the chain — this is purely for display purposes.
   * The creatorAddress below is the authoritative on-chain identity.
   */
  @Column()
  creator: string;

  /**
   * Creator wallet address — 44-character base58 Solana public key.
   * The on-chain identity of the collection's creator. Used in authority checks,
   * on-chain program calls, and marketplace attributions.
   * Max length 44: standard Solana address length. Enforced at the DB level.
   */
  @Column({ length: 44 })
  @Index()  // Index: queries that list a creator's collections filter by this frequently
  creatorAddress: string;

  /**
   * Blockchain — defaults to 'solana' because that is what this entire application is about.
   * Stored for future-proofing: if multi-chain support ever arrives, this field is ready.
   * Future Juan's problem. Current Juan is focused.
   */
  @Column({ default: 'solana' })
  blockchain: string;

  /**
   * Total supply — the maximum number of NFTs in this collection.
   * The hard cap. The ceiling. The "only X of these will ever exist" number.
   * When minted reaches totalSupply, the collection is sold out.
   * Champagne is optional but recommended.
   */
  @Column({ default: 0 })
  totalSupply: number;

  /**
   * Minted count — how many NFTs have been successfully claimed so far.
   * Incremented on every successful mint transaction.
   * Indexed because filtering "show me actively minting collections"
   * involves comparing minted vs totalSupply at query time.
   */
  @Column({ default: 0 })
  @Index()  // Index: minted count comparisons appear in status-transition queries
  minted: number;

  /**
   * Mint price in SOL — what one NFT costs to mint.
   * Stored as high-precision numeric (18 digits, 9 decimal places) to match
   * SOL's lamport precision (10^-9 SOL = 1 lamport). No rounding errors here.
   * The transformer converts Postgres numeric strings to JavaScript floats on read.
   * Optional: some collections are free-to-mint. Generosity encoded in nullable.
   */
  @Column('numeric', { precision: 18, scale: 9, nullable: true, transformer: { to: (v: number | null) => v, from: (v: string | null) => (v == null ? undefined : parseFloat(v)) } })
  price?: number;

  /**
   * Collection status — the current lifecycle state.
   * M-3: Enum gives compile-time safety; DB CHECK constraint (migration 20260605000001) enforces at storage layer.
   * Defaults to DRAFT because every collection starts as an idea before it becomes a reality.
   * Indexed: status is the most common filter in collection list queries.
   */
  // M-3: Enum gives compile-time safety; DB CHECK constraint (migration 20260605000001) enforces at storage layer.
  @Column({ default: CollectionStatus.DRAFT })
  @Index()  // Index: filtering by status is the most frequent operation in list views
  status: CollectionStatus;

  /**
   * Effective status — the resolved, display-ready status that accounts for time-based transitions.
   * C-4: Stored resolved status so findAll() can filter at DB level without JS post-filtering.
   * Updated on every write; sync service refreshes for time-based transitions.
   *
   * Why does this exist alongside `status`?
   * Because `status` can read 'ready' while the mint window has already opened (READY → MINTING).
   * The sync service resolves time-based transitions and writes effectiveStatus once.
   * Then queries filter on effectiveStatus instead of computing transitions on every request.
   * DB-level filtering = fast. JS post-filtering = mounting regret.
   */
  // C-4: Stored resolved status so findAll() can filter at DB level without JS post-filtering.
  // Updated on every write; sync service refreshes for time-based transitions.
  @Column({ nullable: true })
  @Index()  // Index: effectiveStatus is the column used in user-facing list queries
  effectiveStatus?: string;

  /**
   * Featured flag — whether this collection is highlighted on the homepage or discovery page.
   * Set manually by admins for curated, promoted collections.
   * Indexed because homepage queries filter featured=true frequently and need it to be fast.
   */
  @Column({ default: false })
  @Index()  // Index: featured=true queries run on every homepage load — must be fast
  featured: boolean;

  /**
   * Featured rank — the explicit display order for featured collections.
   * Lower numbers surface first; NULL sorts last (falls back to minted DESC).
   * Set by the owner admin's Featured management view so curation isn't hostage
   * to raw mint counts. Only meaningful when featured = true.
   */
  @Column('int', { nullable: true })
  featuredRank?: number;

  /**
   * Mint start date — when the minting window opens.
   * Used for frontend countdown timers and for the sync service's
   * automatic READY → MINTING status transition.
   * Optional: draft collections haven't set a start date yet. They're still dreaming.
   */
  @Column({ nullable: true })
  mintStart?: Date; // When minting starts (for countdown and phase calculation)

  /**
   * End date — when the minting window closes.
   * Used for the sync service's MINTING → COMPLETED transition.
   * Optional: some collections are open-ended (mint until sold out, no hard deadline).
   * The void is eternal; some collections prefer to be too.
   */
  @Column({ nullable: true })
  endDate?: Date; // When minting ends

  /**
   * Traits — the NFT attribute definitions for this collection.
   * JSONB: flexible schema for trait types, rarity weights, and possible values.
   * The DB CHECK constraint (migration) requires this to be an array, not an object.
   * The DNA of the collection's NFTs. Handle with care.
   */
  @Column('jsonb', { nullable: true })
  traits?: Record<string, any>[]; // NFT trait objects — DB CHECK requires this to be an array

  /**
   * Phases — the mint phase configuration array.
   * JSONB because phase structures are complex and evolving:
   * whitelist windows, public windows, price tiers, per-wallet limits.
   * Each phase object is read by the Solana program at mint time.
   * Store the full configuration here so the frontend can render it without extra API calls.
   */
  @Column('jsonb', { nullable: true })
  phases?: Record<string, any>[];

  /**
   * Fund receivers — the treasury split configuration for this collection.
   * JSONB array of { address, basisPoints } objects.
   * The on-chain Solana program splits mint proceeds among these addresses at mint time.
   * This is where the money goes. Configure carefully.
   * The blockchain is permanent. The fund receiver array is written at deploy time.
   * (Future regret is free. Current diligence is priceless.)
   */
  @Column('jsonb', { nullable: true })
  fundReceivers?: Record<string, any>[];

  /**
   * Transaction signature — the Solana txid of the collection's on-chain initialization.
   * The receipt. The proof. The "yes, this happened on the blockchain" verification.
   * Max length 88: standard Solana signature length in base58.
   * Optional until the collection is deployed on-chain.
   */
  @Column({ nullable: true, length: 88 })
  txSignature?: string;

  /**
   * Royalty basis points — secondary market seller fee.
   * 500 = 5%, 1000 = 10%, 250 = 2.5%. Standard NFT royalty encoding.
   * Only indexed in partial indexes for tradable collections (handled in migration).
   * Optional: not every collection has a secondary royalty configured.
   */
  /** Royalty percentage (seller fee basis points, e.g., 500 = 5%) - only indexed for tradable collections */
  @Column('int', { nullable: true })
  royaltyBasisPoints?: number;

  /**
   * Platform fee basis points — the launchpad's cut, added on top of the creator price.
   * 100 = 1%, 250 = 2.5%. Additive: the buyer pays price + platform fee.
   * The business model, encoded as an integer in the database.
   * Transparent to creators who configure it and to buyers who pay it.
   */
  /** Platform fee percentage (basis points, e.g., 100 = 1%) - additive on top of creator price */
  @Column('int', { nullable: true })
  platformFeeBasisPoints?: number;

  /**
   * Mint address — the on-chain Solana address for the collection's deployed mint.
   * The address referenced by token accounts, Metaplex metadata, and marketplace APIs.
   * Empty until on-chain deployment. Indexed because everything cross-references it after deployment.
   * Max length 44: standard Solana public key length.
   */
  /** On-chain mint address for the collection */
  @Column({ nullable: true, length: 44 })
  @Index()  // Index: on-chain lookups and marketplace queries cross-reference by mintAddress
  mintAddress?: string;

  /**
   * Social links — Twitter, Discord, Website.
   * Optional display fields that complete the collection's public identity.
   * Not indexed: display-only, never used as filter conditions in list queries.
   * (If we ever need to search by website URL, Juan will add an index and apologize for laughing earlier.)
   */
  @Column({ nullable: true })
  twitterUrl?: string;

  @Column({ nullable: true })
  discordUrl?: string;

  @Column({ nullable: true })
  websiteUrl?: string;

  /**
   * Updated by — the wallet address of the last user to modify this collection.
   * L-2: Wallet address of the last modifier — populated in updateCollection().
   * The accountability field. Answers "who changed this?" for audit purposes.
   * The blockchain is immutable. This field provides the mutable accountability layer.
   */
  // L-2: Wallet address of the last modifier — populated in updateCollection().
  @Column({ nullable: true })
  updatedBy?: string;

  /**
   * createdAt — set automatically by TypeORM on INSERT. Never manually writable.
   * The birth certificate of the collection. ISO timestamp stored in the database.
   * Covered by composite indexes (createdAt DESC, id DESC) for paginated list queries —
   * a standalone B-tree index was dropped in migration 000019 as redundant.
   */
  @CreateDateColumn()
  createdAt: Date; // Covered by composite indexes (createdAt DESC, id DESC) — standalone B-tree dropped in migration 000019

  /**
   * updatedAt — updated automatically by TypeORM on every save/update.
   * Used for cache-busting, ETags, and "last modified" display.
   * TypeORM manages this field. Do not write to it manually.
   * TypeORM has very strong opinions about this. We agree with them.
   */
  @UpdateDateColumn()
  updatedAt: Date;

  /**
   * deletedAt — the soft delete timestamp.
   * Null = collection is live and visible.
   * Non-null = collection was soft-deleted, excluded from all standard queries automatically.
   *
   * L-1: Soft delete. TypeORM find/findOne automatically exclude rows where deletedAt IS NOT NULL.
   * QueryBuilder does NOT auto-exclude — add .andWhere('c.deletedAt IS NULL') explicitly there.
   *
   * Soft deletes: the humane way to remove data.
   * The collection is hidden from all queries but recoverable if a mistake was made.
   * (Mistakes are made. Soft deletes are why we sleep at night.)
   */
  // L-1: Soft delete. TypeORM find/findOne automatically exclude rows where deletedAt IS NOT NULL.
  // QueryBuilder does NOT auto-exclude — add .andWhere('c.deletedAt IS NULL') explicitly there.
  @DeleteDateColumn({ nullable: true })
  deletedAt?: Date;
}

// ─────────────────────────────────────────────────────────────────────────────
// Signed: Juan
// Role: Schema designer, index strategist, keeper of the sacred collection data
// Opinions held strongly:
//   - Every @Index() here was added because a specific query needed it.
//     Indexes cost write performance and storage. Each one earns its keep.
//   - effectiveStatus exists because time-based status transitions are expensive
//     to compute in JavaScript for every list query. The sync service does the work
//     once; the index makes the query fast. Everyone wins.
//   - phases and fundReceivers are JSONB because their structure evolves.
//     JSONB in Postgres is not a schema cop-out — it is the right tool for
//     configuration data with variable shape. We use it deliberately.
//   - If you add a column: write a migration. Run it. Check it into git.
//     Do not touch synchronize: true. TypeORM's synchronize will someday
//     drop a column you need. That day will be bad.
//     Write the migration. Sleep soundly.
// ─────────────────────────────────────────────────────────────────────────────
