/**
 * programs.ts
 *
 * Program metadata and IDL loader for the unified Nexus Launchpad.
 *
 * It was three programs. Sprawling, overlapping, lovingly named.
 * Now it is one. The IDL is generated by:
 *   anchor build -- --no-default-features --features idl-build
 * Output lands in programs/target/idl/nexus_launchpad.json.
 * Copy it here after each build. Do not skip this step.
 * (Skipping this step is how we end up sending the wrong instruction data
 *  to the chain and discovering the hard way that the discriminator changed.
 *  The chain will not warn you. The chain will just reject the transaction.
 *  Cryptographically. With prejudice.)
 *
 * The two ghosts still haunting this directory —
 * nexus_collection.json and nexus_payment.json — are dead.
 * Delete them when you find them. Let them rest.
 *
 * "Three programs became one. Just like three Starbucks visits became one
 *  long, continuous caffeine dependency." — Juan
 */

// PROGRAM_ID: the 32-byte address that identifies our program on-chain.
// The IDL knows this address. The chain knows this address. Now this file knows too.
import { PROGRAM_ID } from './constants';

// fs and path: the OG Node.js modules.
// We're doing file I/O to load the IDL at startup — because IDLs are big JSON files
// and nobody wants to inline a 500-line JSON object into TypeScript. Not even Juan.
import * as fs from 'fs';
import * as path from 'path';

/**
 * ProgramMetadata
 *
 * The shape of a program descriptor. Three fields:
 * - id:  the on-chain address (string, base58)
 * - name: a human-readable label for logs, dashboards, and post-mortems
 * - idl:  the Interface Definition Language — the schema of all instructions,
 *         accounts, and types. If it's null, the IDL hasn't been generated yet.
 *         Run anchor build. We'll wait.
 *
 * (We will not actually wait. The app starts regardless. IDL is optional at runtime.
 *  But some features that depend on it will silently do nothing. Which is worse.)
 */
export interface ProgramMetadata {
  id: string;
  name: string;
  idl: any; // "any" because IDL schemas are big, untyped JSON and life is short.
}

/**
 * loadIdl
 *
 * Attempts to load an IDL JSON file from the ./idl/ subdirectory next to this file.
 * Returns the parsed JSON if it exists, null if it doesn't.
 *
 * The null case is intentional and handled gracefully. This function will not throw.
 * It will not panic. It will not spiral. It will return null with the quiet dignity
 * of someone who has accepted that the IDL might not be generated yet.
 *
 * To generate the IDL:
 *   anchor build -- --no-default-features --features idl-build
 * (Yes, that flag looks weird. No, you can't omit it. The IDL feature must be explicit.
 *  Anchor chose this life. We inherited it.)
 *
 * @param {string} filename - The IDL JSON filename (e.g., 'nexus_launchpad.json').
 * @returns {any | null} Parsed IDL object, or null if the file isn't there yet.
 */
function loadIdl(filename: string): any {
  try {
    // __dirname: the directory of this compiled file (dist/solana/).
    // The IDL lives in dist/solana/idl/ at runtime — so we join accordingly.
    // If you're wondering why path.join is needed here: Windows. Always Windows.
    const idlPath = path.join(__dirname, 'idl', filename);
    // Synchronous read because this runs at module load time,
    // not during a request. It's acceptable. We've made peace with it.
    return JSON.parse(fs.readFileSync(idlPath, 'utf8'));
  } catch {
    // The IDL file doesn't exist yet. That's okay. Kind of.
    // It means someone forgot to run anchor build. Or the file wasn't copied over.
    // Or the --features flag was missed. The error message in the catch block
    // would tell us, but we swallow it here and return null because:
    //   a) the app should still start without the IDL
    //   b) ContractsService does manual Borsh encoding anyway, so it doesn't need it
    //   c) logging here would be noisy on first install
    // Note to future Juan: if something is broken and silent, check this first.
    // IDL file not yet generated — run: anchor build -- --no-default-features --features idl-build
    return null;
  }
}

/**
 * PROGRAM
 *
 * The singleton descriptor for the Nexus Launchpad program.
 * One program. One object. One place to look when you need to know
 * what address we're deployed at, what we're called, and what our IDL looks like.
 *
 * idl will be null until you run anchor build and copy the output.
 * The rest of the app doesn't strictly need the IDL at runtime —
 * but tools, explorers, and future automatic instruction builders will.
 * So keep the IDL up to date. Commit it. Review it.
 * It is the receipt for everything the smart contract can do.
 * And unlike receipts in real life, this one actually matters.
 */
export const PROGRAM: ProgramMetadata = {
  // The on-chain address. Changes per deployment, hence the env var.
  id: PROGRAM_ID,
  // The human name. Used in logs and maybe a dashboard someday.
  name: 'Nexus Launchpad',
  // The IDL: loaded from disk at startup. null if not yet generated.
  // null means "anchor build hasn't been run" or "the file wasn't copied."
  // Either way: go run anchor build. It's fine. It takes a minute.
  idl: loadIdl('nexus_launchpad.json'),
};

/**
 * getProgramIdl
 *
 * Convenience accessor for the program's IDL.
 * Returns the parsed IDL object, or null if it wasn't loaded.
 *
 * Callers should handle the null case — not because it's common,
 * but because it's honest. The IDL is not always available.
 * We acknowledge that. We plan for it. We mention it in the comments.
 * (This is called "documentation." It is rare and precious.)
 *
 * @returns {any | null} The IDL JSON object, or null. Life is non-deterministic.
 */
export function getProgramIdl(): any {
  return PROGRAM.idl;
}

// ─────────────────────────────────────────────────────────────────────────────
// Juan was here.
//
// This file used to juggle three programs. Now it manages one.
// The consolidation was correct. The cleanup is ongoing.
// nexus_collection.json and nexus_payment.json are haunting the idl/ directory
// like ghosts of architectural decisions past. Delete them when you find them.
//
// The IDL is the contract's interface — the handshake between on-chain Rust
// and off-chain TypeScript. Keep them in sync.
// When the Rust changes, regenerate the IDL.
// When the IDL changes, update the Borsh encoding in contracts.service.ts.
// When the encoding drifts from the chain, the transaction fails silently.
// The chain doesn't apologize. The chain doesn't explain.
// The chain just rejects your instruction data and moves on to the next block.
//
// Permanent, remember? On-chain means permanent.
// But the IDL file is not on-chain. It lives here, in a directory,
// tracked by git, and subject to human forgetfulness.
// Update it. Every time.
//
//  — Juan, IDL Shepherd, Ghost Program Exorcist, Anchor Build Evangelist
// ─────────────────────────────────────────────────────────────────────────────
